### ISSUE TITLE
XPath not working no matter what I try

### ISSUE THREAD

**Issue by Skinner007** [goto100/xpath#102]
I'm trying to use XPath with xmldom in typescript to parse a trx file, but nothing I try will yield a single node selected.

Sample stripped down trx XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="9db027c9-51f8-4619-aadb-34217a78b543" name="SomeName" runUser="SomeUser" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
	<ResultSummary outcome="Completed">
		<Counters total="21" executed="21" passed="21" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
		<Output>
			<StdOut>Data collection : Logging DataCollector Diagnostics in file: D:\SomeFile.txt&#xD;
Logging TestHost Diagnostics in file: D:\SomeFile.txt&#xD;
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit Desktop .NET 4.0.30319.42000)&#xD;
[xUnit.net 00:00:00.81]   Discovering: SomeClass&#xD;
[xUnit.net 00:00:00.90]   Discovered:  SomeClass&#xD;
[xUnit.net 00:00:00.91]   Starting:    SomeClass&#xD;
[xUnit.net 00:00:01.36]   Finished:    SomeClass&#xD;
			</StdOut>
		</Output>
		<CollectorDataEntries>
			<Collector agentName="AgentName" uri="datacollector://microsoft/CodeCoverage/2.0" collectorDisplayName="Code Coverage">
				<UriAttachments>
					<UriAttachment>
						<A href="AgentName\SomeFile.coverage"/>
					</UriAttachment>
				</UriAttachments>
			</Collector>
		</CollectorDataEntries>
	</ResultSummary>
</TestRun>
```

Stripped down ts:

```
import fs = require('fs');
import { DOMParser } from 'xmldom';
import xpath = require('xpath');

const content = fs.readFileSync(filePath, 'utf8');
const doc = new DOMParser().parseFromString(content, 'text/xml').documentElement;
```

at this point doc.nodeName is TestRun.

This yields 0 results

    xpath.select('//Collector[@collectorDisplayName="Code Coverage"]//A/@href', doc);

This yields 0 results

```
const ns = doc.namespaceURI!;// <-- the value here is the expected namespace from the TestRun node
const select = xpath.useNamespaces({ "ns": ns })
const refs = select('//ns:Collector[@collectorDisplayName="Code Coverage"]//A/@href', doc);
```

I've tried all combinations of xpath with and without the ns:. All of the following are valid and tested with online xpath evaluators, but none work with this module.

`//A`
`//a`
`//A/@href`
`//Collector[@collectorDisplayName="Code Coverage"]//A/@href`
`//TestRun`
`//*`

What am I missing?

**Comment by JLRishe** [comment]
The second attempt you showed was close, but doesn't work because you do not have a prefix on `A`. Every element in your XML is in the `http://microsoft.com/schemas/VisualStudio/TeamTest/2010` namespace, so you need a prefix on every element step in your XPath:

```javascript
const ns = 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010';
const select = xpath.useNamespaces({ "ns": ns });
const refs = select('//ns:Collector[@collectorDisplayName="Code Coverage"]//ns:A/@href', doc);
```

I would also advise against the use of `//` unless there is a compelling reason for it, because `//` is bad for performance. It looks like the following should be good in your case:

```javascript
const ns = 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010';
const select = xpath.useNamespaces({ "ns": ns });
const refs = select('/ns:TestRun/ns:ResultSummary/ns:CollectorDataEntries/ns:Collector[@collectorDisplayName="Code Coverage"]/ns:UriAttachments/ns:UriAttachment/ns:A/@href', doc);
```

**Comment by Skinner007** [comment]
That worked! I'm not going to admit how long I was banging my head on this.

The only question I have now: The result of the select is XPathSelect[], and the string value is ' href="AgentName\SomeFile.coverage"' (single quotes to show the full value are not part of the value). How do I get just the value of the href and not the attribute name with the leading space?

**Comment by JLRishe** [comment]
When the XPath expression used evaluates to a nodeset, as it does here, the returned value is an array of DOMNodes.

In your case, you are selecting an attribute, so you get an [Attr](https://developer.mozilla.org/en-US/docs/Web/API/Attr). You can obtain its value from its `.value` property:

const ns = 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010';
const select = xpath.useNamespaces({ "ns": ns });
const refs = select('/ns:TestRun/ns:ResultSummary/ns:CollectorDataEntries/ns:Collector[@collectorDisplayName="Code Coverage"]/ns:UriAttachments/ns:UriAttachment/ns:A/@href', doc);

const hrefValues = hrefs.map(n => n.value);

**Comment by JLRishe** [comment]
@Skinner007 Please let me know if you're still having trouble after the above response.
