### ISSUE TITLE
Update references to XMLDOM?

### ISSUE THREAD

**Issue by cburatto** [goto100/xpath#105]
### Not an issue, but a question/suggestion

xpath documentation and dependencies refer to older, unmaintained XMLDOM version `0.1.19` from 

https://github.com/jindw/xmldom

But XMLDOM development proceeds on new location, currently version `0.4.0`

https://github.com/xmldom/xmldom

I know xpath is engine agnostic, but maybe it would make sense to update references and dependencies to active xmldom. Any known issues?

**Comment by JLRishe** [comment]
Thanks!
