### ISSUE TITLE
Licensing history

### ISSUE THREAD

**Issue by hyandell** [goto100/xpath#110]
Hi @goto100,

Could you describe the licensing history for the project? I see that it has moved to MIT, but looking at the old issues all I can find are questions about the licensing and not the history of how the original author's approval was given to relicense to MIT and remove the Creative Commons identification.

**Comment by JLRishe** [comment]
Hello @hyandell,

Looking at the edit history of package.json will lead you to #76, which links to yaronn#20 (from another fork of this same library), where the original author assents to making the license MIT.

**Comment by hyandell** [comment]
Thank you @JLRishe - sorry for not figuring that out :(

**Comment by JLRishe** [comment]
No problem! Thanks for inquiring.
