### ISSUE TITLE
xmldom dependency has a security issue

### ISSUE THREAD

**Issue by karfau** [goto100/xpath#111]
Latest versions of the `xmldom` lib are now only published as `@xmldom/xmldom`, so to update from version 0.6.0 [which is known to be vulnerable](https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q), it's required to switch to the scoped package. For more details see https://github.com/xmldom/xmldom/issues/271

I'm one of the maintainers (of the xmldom package) and I can support any update issues if you want.

It would be good to also update the example code in the readme.

**Comment by JLRishe** [comment]
@karfau Thank you for the details. I'll try to get this taken care of soon.
