### ISSUE TITLE
An example of using it with regular HTML?

### ISSUE THREAD

**Issue by OnkelTem** [goto100/xpath#115]
Please could you provide an example of using it with HTML?
Specifically, is there a way to go with default namespacing? The documentation section on this is missied.

**Comment by JLRishe** [comment]
We don't have documentation on this, but you can evaluate XPaths in HTML mode by using a [parsed expression](https://github.com/goto100/xpath/blob/master/docs/parsed%20expressions.md) and passing `isHtml: true` when evaluating it.

See example here:  
https://github.com/goto100/xpath/issues/27#issuecomment-1041378729

This would allow you to use XPath on an HTML document without namespace prefixes.
