### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by alitavector** [goto100/xpath#13]
```
var nodes = xpath.select("//measure/note/pitch", doc)
```

How do I reuse the nodes variable to select /pitch/step and  /pitch/octave instead of typing out full path?

**Comment by JLRishe** [comment]
I don't think the Node.js wrapper for this library currently supports using `nodes` (which is an array of nodes) as a starting point for a subsequent query, but you can perform a queries using each of those nodes as a starting point:

    var nodes = xpath.select("//measure/note/pitch", doc);
    for (var i = 0; i < nodes.length; i += 1) {
        var step = xpath.select1('step', nodes[i]);
        var octave = xpath.select1('octave', nodes[i]);
    }

**Comment by JLRishe** [comment]
I'm pretty sure that in your case, looping through the nodes and evaluating relative paths on each node (as shown above) is what you'd want to do anyway. Please let me know if that's not the case.
