### ISSUE TITLE
substring-after() does not work correctly

### ISSUE THREAD

**Issue by JLRishe** [goto100/xpath#14]
The implementation of `substring-after()` is incorrect. It actually returns everything after the first character of the second argument.

Example:
`substring-after("some of my favorite things", "favor")`
Expected: `ite things`
Actual: `avorite things`

**Comment by JLRishe** [comment]
Submitted pull request for proposed fix.
https://github.com/goto100/xpath/pull/15

**Comment by goto100** [comment]
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/substring-after

**Comment by goto100** [comment]
OK, I found it.

http://www.w3.org/TR/xpath/#function-substring-after
