### ISSUE TITLE
XPathException does not act like an Error

### ISSUE THREAD

**Issue by JLRishe** [goto100/xpath#22]
This library has an `XPathException` type that is thrown in about 4 places in the code, but it was not designed to have the functionality of an `Error`: it doesn't contain a stack trace or a `.message` property. 

When an `XPathException` is thrown during nodeunit execution, the output just says `undefined` instead of showing a message and stack trace this makes it hard to track down bugs.

I have added a fix for this issue and will be submitting a pull request.

**Comment by neu-rah** [comment]
+1
