### ISSUE TITLE
Remove Creative Commons license reference

### ISSUE THREAD

**Issue by jlamondw** [goto100/xpath#26]
The package.json specifies MIT license, but xpath.js says that it's licensed under Creative Commons Attribution-ShareAlike license.

**Comment by JLRishe** [comment]
The original library was released under the Creative Commons Attribution-Sharealike license, which includes this stipulation:

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. 

So it would be a violation of the license to remove the license reference. If anything, I would say that package.json should be corrected. Would you concur?

**Comment by jlamondw** [comment]
Yeah, updating package.json to reflect that makes sense.
