### ISSUE TITLE
createExpression hangs on certain invalid expressions

### ISSUE THREAD

**Issue by zorkow** [goto100/xpath#28]
Seems to enter an infinite loop on expressions like:
xpath.createExpression('self::text() = "\""');
xpath.createExpression("self::text() = '\''");
or even simpler
xpath.createExpression('"\""');

Expected behaviour: Throw Invalid expression.

**Comment by JLRishe** [comment]
I have committed a fix for this on my fork of the project. It seems that goto100 is not currently watching pull requests.

**Comment by zorkow** [comment]
Great, thanks. Will that also make it into the version available with npm?

**Comment by JLRishe** [comment]
@zorkow Yes, I haven't done an npm update before, but I am an owner on the project, so I will push out an update in the next few days.

**Comment by JLRishe** [comment]
Sorry this has taken so very long, but I have published out an update to NPM.
