### ISSUE TITLE
select on attribute returning only first element

### ISSUE THREAD

**Issue by shadiakiki1986** [goto100/xpath#37]
If I try to select on a particular attribute (such as `value` in the below snippet), the returned array of the select call is of length 1, whereas there should be 2 matches
```
  var xpath = require('xpath')
    , dom = require('xmldom').DOMParser

  var xml = "<book><title value='1'>Harry Potter</title><title value='2'>ba2ra</title></book>"
  var doc = new dom().parseFromString(xml)
  var nodes = xpath.select("//title/@value", doc)
  console.log(nodes.length)
```

However, if I select on the node name, and then return the attribute via getAttribute, then I get an array of length 2
````
  var xpath = require('xpath')
    , dom = require('xmldom').DOMParser
  var xml = "<book><title value='1'>Harry Potter</title><title value='2'>ba2ra</title></book>"
  var doc = new dom().parseFromString(xml)
  var nodes = xpath.select("//title", doc)
  nodes = nodes.map(function(x) { return x.getAttribute("@value"); });
  console.log(nodes.length)
````

I created a [pull request](https://github.com/goto100/xpath/pull/38) with added unit tests for this issue

**Comment by JLRishe** [comment]
Thank you for pointing this out. It should be fixed now.
