### ISSUE TITLE
Not matching multiple attributes in later versions, older version in reverse order.

### ISSUE THREAD

**Issue by angas** [goto100/xpath#41]
Code below shows a difference introduced between version 0.0.9 and 0.0.20. Probably the correct output should be `[ '1', '2', '3' ]`.

```
var dom = require('xmldom').DOMParser;
var xpath = require('path');
var doc = new dom().parseFromString('<e1><e2 v="1"/><e2 v="2"/><e2 v="3"/></e1>');
var nodes = xpath.select("/e1/e2/@v", doc);
console.log(nodes.map(function (n) { return n.value }));

// 0.0.9  => [ '3', '2', '1' ]
// 0.0.20 => [ '1' ]
```

**Comment by JLRishe** [comment]
The main issue mentioned here is the same as https://github.com/goto100/xpath/issues/37

I have now published an update to the npm package and aside from the misspelled package name, the code above works as expected in version 0.0.22.

**Comment by angas** [comment]
Really kind of you to fix this so quickly!

Regards
Andreas



On 2 mars 2016 at 12:10:10, Jimmy Rishe (notifications@github.com) wrote:

The main issue mentioned here is the same as #37

I have now published an update to the npm package and aside from the misspelled package name, the code above works as expected in version 0.0.22.
