### ISSUE TITLE
Context position issue

### ISSUE THREAD

**Issue by scottdixon** [goto100/xpath#45]
Thanks for the great package.

Take the following XML:

```
<myXml>
  <items>
    <item>Item 1</item>
    <item>Item 2</item>
  </items>
  <items>
    <item>Item 3</item>
    <item>Item 4</item>
  </items>
</myXml>
```

`myXml/items/item[1]` should return the first `item` in each `items` (Items 1 & 3). However, only one item is returned (Item 1).

I suspect this is because https://github.com/goto100/xpath/blob/master/xpath.js#L1704-L1709 increments the contextPosition for each match.

Reseting the context on each new parent seems to work but this breaks other selectors. I can wrap this in a conditional - Is there a more elegant solution off the top of your head?

**Comment by JLRishe** [comment]
Thank you for reporting this. I will look into it when I can.

One workaround in the meantime is to use:

```
 myXml/items/item[not(preceding-sibling::*)] 
```

to get the first child of each parent or

```
myXml/items/item[count(preceding-sibling::*) = N] 
```

to get the N+1th child.

Not at all ideal, I know, but I have verified that both of these expressions produce the expected result.

**Comment by scottdixon** [comment]
Thanks, appreciate it!

**Comment by rromanw** [comment]
+1

**Comment by JLRishe** [comment]
@scottdixon  @rromanw Sorry it took so long to fix this. I believe it is working now. Please let me know if you still see any issues.
