### ISSUE TITLE
CDATA section isn't parsed correctly

### ISSUE THREAD

**Issue by aexmachina** [goto100/xpath#46]
Here's an example:

```js
const xpath = require('xpath');
const DOMParser = require('xmldom').DOMParser;

var doc;
doc = new DOMParser().parseFromString('<foo>bar</foo>');
console.log(xpath.select('//foo/text()', doc).toString()); // => 'bar'
doc = new DOMParser().parseFromString('<foo><![CDATA[bar]]></foo>');
console.log(xpath.select('//foo/text()', doc).toString()); // => '<![CDATA[bar]]>'
```

I would expect the output to be:

```
bar
bar
```

But it doesn't strip out the CDATA delimiters.

**Comment by aexmachina** [comment]
Looks like the solution is:

```
xpath.select(`string(//foo/text())`, doc)
```

Maybe you should add this to the docs?

**Comment by JLRishe** [comment]
I will consider adding this to the docs, but this isn't a bug. The problem is that you're using `.toString()` when you should't, and this has come up in the past:

https://github.com/goto100/xpath/issues/30

**Comment by aexmachina** [comment]
The README provides `.toString()` in an [example](https://github.com/goto100/xpath#get-text-values-directly]:

```js
var xml = "<book><title>Harry Potter</title></book>"
var doc = new dom().parseFromString(xml)
var title = xpath.select("//title/text()", doc).toString()

console.log(title)
```

**Comment by JLRishe** [comment]
@aexmachina Thank you for pointing that out. I have amended the README to use a `string()` function.
