### ISSUE TITLE
processing-instruction('{{target}}') does not work

### ISSUE THREAD

**Issue by grantcv1** [goto100/xpath#48]
While you can search for all processing instructions using processing-instruction(), specifying a target returns undefined (not even an empty array)

**Comment by JLRishe** [comment]
I believe this is an issue with the library's xpath parser, which has a rather opaque implementation and I'm not entirely sure how to add this functionality.

As a workaround, you can use `processing-instruction()[local-name() = '{{target}}']`.

**Comment by JLRishe** [comment]
@grantcv1 Sorry this took so long to fix. This should be working now.

**Comment by Lilipi** [comment]
It's working now, thanks !
