### ISSUE TITLE
The preceding:: axes does not work

### ISSUE THREAD

**Issue by grantcv1** [goto100/xpath#49]
If you call:

xpath.select1("preceding::processing-instruction()", contextNode)

you get the first node in the document rather than the node prior to the context node.

**Comment by JLRishe** [comment]
Sounds like what you're describing is expected behavior. `select1` returns the first item in the node set in document order.

To select the nearest processing instruction, use:

    xpath.select1("preceding::processing-instruction()[1]", contextNode)
