### ISSUE TITLE
Whitespace causes nextSibling to get it wrong

### ISSUE THREAD

**Issue by technorodent** [goto100/xpath#51]
This case occurs if using xmldom and xpath: 

> If an xml file has whitespace introduced, such as through formatting in Visual Studio or another formatting medium, the .nextSibling.textContent will choose the whitespace over the next node. For example:

Given xml:

`<row id="1468866500749"><cell>Tourist Information</cell><cell>SPO/About-South-Pole-Station/Tourist-Information/</cell><cell>ca229252acb13e1ed15a28ac25c412ce</cell><cell>1</cell><cell/></row>`

And this code:

```
views.get('/*', function (req, res) {
     var nodes = xpath.select("//cell[text()='SPO" + req.url + "']", menuDoc);
     var addr = nodes[0].nextSibling.textContent;
     ...
```

The variable addr will correctly return: ca229252acb13e1ed15a28ac25c412ce.

Given xml:
```
<row id="1468866500749">
        <cell>Tourist Information</cell>
        <cell>SPO/About-South-Pole-Station/Tourist-Information/</cell>
        <cell>ca229252acb13e1ed15a28ac25c412ce</cell>
        <cell>1</cell>
        <cell/>
</row>
```
And this code:
```
views.get('/*', function (req, res) {
     var nodes = xpath.select("//cell[text()='SPO" + req.url + "']", menuDoc);
     var addr = nodes[0].nextSibling.textContent;
     ....
```
The variable addr will return a carriage return and spaces.

By doing the following to an xml string in advance prevents the error:
```
str = str.replace(/>\s*/g, '>');  // Remove white space after >
str = str.replace(/\s*</g, '<');  // Remove white space before <
```

**Comment by JLRishe** [comment]
The problem you're describing has nothing to do with this library. The `nodes[0]` in your code obtains an XML node and this library has no control over what you do with that node or what its siblings are.

Additionally, the behavior you're seeing is correct. The next sibling of that `<cell>` element is a whitespace text node, and that's what you're getting.

You can utilize XPath to obtain the node you actually want:

    var node = xpath.select1("//cell[text()='SPO" + req.url + "']/following-sibling::cell", doc);
    var addr = node.textContent;

**Comment by technorodent** [comment]
Thanks!
