### ISSUE TITLE
register custom functions?

### ISSUE THREAD

**Issue by TomBZombie** [goto100/xpath#55]
Is there any way this could allow registering of custom functions? e.g.

``` js

xpath.registerFunction('customFilter', function(element, args) {
    if (element.getAttribute('foo') > 10 && args[0] == 'true') {
        return true;
    }
    else {
        return false;
    }
});


xpath.select('//customFilter(true)', doc);
```

This is possible in most languages such as PHP, I was wondering if this is possible here?

**Comment by JLRishe** [comment]
There is a way to do this. I will document it when I have the time to do so.

**Comment by JLRishe** [comment]
I know this is a fairly old question, but I've finally added [documentation](https://github.com/goto100/xpath/blob/master/docs/parsed%20expressions.md) on the APIs for doing this. 

In your case, the code would look something like this:

 ```js 

var expr = xpath.parse('//*[customFilter(true())]');

var nodes = expr.select({
    node: doc,
    functions {
        customFilter: function (context, arg) {
            return context.contextNode.getAttribute('foo') > 10 &&
                       arg.booleanValue();
       }
    }
});
```
