### ISSUE TITLE
does not work with mime type text/html

### ISSUE THREAD

**Issue by TomBZombie** [goto100/xpath#56]
a small adjustment to the sample code stops it working:

```js
var xpath = require('xpath')
  , dom = require('xmldom').DOMParser
 
var xml = "<book><title>Harry Potter</title></book>"
var doc = new dom().parseFromString(xml, 'text/html');
var nodes = xpath.select("//title", doc)

console.log(nodes);
```

`nodes` is an empty array.

I don't know whether this is an issue with xmldom or xpath but this fixes it:

```js
var xpath = require('xpath')
  , dom = require('xmldom').DOMParser
  , serializer = require('xmldom').XMLSerializer;
 
var xml = "<book><title>Harry Potter</title></book>"
var doc = new dom().parseFromString(new serializer().serializeToString(new dom().parseFromString(xml, 'text/html')));
var nodes = xpath.select("//title", doc)

console.log(nodes);
```

Obviously this is terribly inefficient but it does work.

**Comment by JLRishe** [comment]
There's already an open issue #27 on this. The library works with this mime type, but parsing with that mime type implicitly puts the nodes in the `http://www.w3.org/1999/xhtml` namespace. That's why you're not finding any matches with `//title`.
