### ISSUE TITLE
Nested Searching 

### ISSUE THREAD

**Issue by ponyesteves** [goto100/xpath#62]
When itereating an array from a search result and applying another search in a ITEM,  it retrive results form the entire document. 
```js
let cfes = xpath.select("//*[local-name(.)='CFE']", doc)
for (let cfe of cfes){
  let Encabezado = xpath.select("//*[local-name(.)='Encabezado']", cfe)
}
```

The only workaround I found untill know is adding this line of code inside the for loop
   cfe = new dom().parseFromString(cfe.toString())... 

```js
let cfes = xpath.select("//*[local-name(.)='CFE']", doc)
for (let cfe of cfes){
  cfe = new dom().parseFromString(cfe.toString())
  let Encabezado = xpath.select("//*[local-name(.)='Encabezado']", cfe)
}
```

But surely is not the most efficient way of doing this. 

Is there a cleaner way fo achieving the same?

**Comment by JLRishe** [comment]
It's searching the whole document because you're using an absolute path. Use a relative path instead:

    let Encabezado = xpath.select(".//*[local-name(.)='Encabezado']", cfe)

**Comment by ponyesteves** [comment]
@JLRishe Thank. that work perfectly!

**Comment by Aldaviva** [comment]
This answer is correct, and I wanted to add a clarifying example because I was confused about the exact usage. Hopefully this will help someone with the same question.

## XML
```xml
<?xml version="1.0" encoding="UTF-8"?>
<outer>
  <middle wanted="false">
    <inner>This is not the text I wanted</inner>
  </middle>

  <middle wanted="true">
    <inner>This is the text I want</inner>
  </middle>
</outer>
```

## Javascript
```javascript
var xmlString; //populate this with the XML above; for example you could use fs.readFile in Node.js
var domParser = new DOMParser();
var doc = domParser.parseFromString(xmlString, "application/xml");

var wantedMiddleNode = xpath.select("/outer/middle[@wanted='true']", doc)[0];
var wantedText = xpath.select("./inner/text()", wantedMiddleNode);

console.log("inner text = " + wantedText); //prints node text = This is the text I want
```

I was confused because even though `wantedMiddleNode.toString()` returns
```xml
<middle wanted="true">
  <inner>This is the node I want</inner>
</middle>
```
you have to query `wantedMiddleNode` without the top-level `<middle>` element, `./inner/text()`, instead of `./middle/inner/text()`.

If you want your queries to be portable regardless of whether you're using an entire document or just a child element, you can start all your queries with `./`.

**Comment by JLRishe** [comment]
@Aldaviva The `./` in your example doesn't actually add any benefit. It's necessary in ponyesteves' case because he's using `//` and `//` will traverse the whole document if there isn't something before it.

In your case `inner/text()` would suffice.

**Comment by Aldaviva** [comment]
Ah okay. I reran my tests without the leading `./` and it still works. I must have changed something else at the same time I added the `./` and falsely attributed the fix to the wrong change.
