### ISSUE TITLE
Declared license 

### ISSUE THREAD

**Issue by sgustafsson** [goto100/xpath#69]
The license of this module has beenchanged to Attribution 4.0 International (CC-BY-4.0). As the original code was released "under under the Creative Commons Attribution-ShareAlike License", I wonder how the license can now be CC-BY-4.0 . By this switch, the "ShareAlike" obligations of the original license were dropped. 

Can you explain the reasonsing why CC-BY-4.0 was chosen (and not CC-BY-SA-2.0) ?

**Comment by JLRishe** [comment]
I am simply maintaining the code in this project and am not very knowledgeable about licenses. There were some open issues requesting changes to the project.json and the inclusion of license text, and someone made a pull request so I accepted it:
https://github.com/goto100/xpath/pull/61

I agree that it doesn't seem to be quite the right license. Could you tell me where I should obtain the text for the correct license? I know about [this](https://creativecommons.org/licenses/by-sa/2.0/?), but I don't know the correct way to represent that in text form.

**Comment by sgustafsson** [comment]
In your package.json, you need to specify the license name in the so called SPDX format, see https://docs.npmjs.com/files/package.json#license , in your case https://spdx.org/licenses/CC-BY-SA-2.0.html -> CC-BY-SA-2.0

As the author of the original version of the code - Cameron McCormack - licensed the code under CC-BY-SA-2.0, the "Share Alike" effect of this license basically makes every successor version of the code licensed under the exact same license. That's why I was wondering why the license in this repo was changed to CC-BY-4.0

**Comment by JLRishe** [comment]
I have changed the license name in the package.json, and deleted the LICENSE file. Will reopen issue #5.
