### ISSUE TITLE
Will waste your time until you realize this just does not work for more complex XML

### ISSUE THREAD

**Issue by cmdematos** [goto100/xpath#73]
In typical Node hacker quality, this library and the others named for it (also called xpath and xpath,js) this simply does not work. You will get Nada! as per below for really simple queries that work NIGHT AND DAY in more mature tools, you know stuff like Java and C# and *gasp* even PHP!

        let xml =
            '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">' +
            '<modelVersion>4.0.0</modelVersion>' +
            '<parent>' +
            '<groupId>org.apache.geronimo.genesis.config</groupId>' +
            '<artifactId>project-config</artifactId>' +
            '<version>1.3.1</version>' +
            '</parent>' +
            '<groupId>com.softbrands</groupId>' +
            '<artifactId>master</artifactId>' +
            '<name>${}Master POM</name>' +
            '<packaging>pom</packaging>' +
            '<version>3.2-SNAPSHOT</version>' +
            '</project>' +
            '';
        let xdoc = new dom().parseFromString(xml);
        let title = xpath.select("/project/*[local-name() = 'version']", xdoc);
        if (title[0]) {
            title.forEach((n) => {
                console.log(`===============> ${n.toString()}`);
            });
        } else {
            console.log('Nada!');
        }
    }

Yup! Its good for Nada! You can reformat and paste the XML and the query into any online tool, like this one https://www.freeformatter.com/xpath-tester.html#ad-output to see that xpath does not belong in any release status.

**Comment by JLRishe** [comment]
Please don't blame this library for your incomplete understanding of XPath. It works fine for what you're trying to do. The problem is that you haven't declared the namespaces you need, which is something you would have to do in Java, C#, PHP, and virtually any XPath library worth its salt. [Here is the C# equivalent of your failed attempt to use this library.](https://ideone.com/jUOGSw)

Working code([run it on runkit](https://runkit.com/jlrishe/runkit-npm-xpath-issue73)):
```javascript
 let xpath= require('xpath')
 let dom = require('xmldom').DOMParser
 
 let xml =
        '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">' +
        '<modelVersion>4.0.0</modelVersion>' +
        '<parent>' +
        '<groupId>org.apache.geronimo.genesis.config</groupId>' +
        '<artifactId>project-config</artifactId>' +
        '<version>1.3.1</version>' +
        '</parent>' +
        '<groupId>com.softbrands</groupId>' +
        '<artifactId>master</artifactId>' +
        '<name>${}Master POM</name>' +
        '<packaging>pom</packaging>' +
        '<version>3.2-SNAPSHOT</version>' +
        '</project>' +
        '';
let xdoc = new dom().parseFromString(xml);
let select = xpath.useNamespaces({ maven: 'http://maven.apache.org/POM/4.0.0' });
let title = select("/maven:project/maven:version", xdoc);
if (title[0]) {
    title.forEach((n) => {
        console.log(`===============> ${n.toString()}`);
    });
} else {
    console.log('Nada!');
}
```

**Comment by cmdematos** [comment]
Bullshit. 

I consider my post both an open ticket as well as a PUBLIC SERVICE ANNOUNCEMENT and your reply is total bullshit from a script-kiddie. Your code is broken and does not handle the xpath that should ignore the presence of the namespace correctly. I should not have to say 'use namespace' with this query, which does not work as well...

'/project/*[local-name() = "version"]'

It should be noted that your solution requires that I first know whether my document uses namespaces, and not all of them do, and documents with them or without them remain valid. All the major libraries I have tried in Java process my xpath correctly. 

But you are correct that I am not an XML specialist having seldom needed to used it over the last two decades, yet I managed to have my code work in 4 different libraries in about an hour. 

Lastly, if you dont like my post, delete it. But dont show everyone you are the prototypical 'kiddie' in script-kiddie by changing my title.

**Comment by JLRishe** [comment]
> Your code is broken and does not handle the xpath that should ignore the presence of the namespace correctly.

Wrong. The XPath 1.0 spec clearly states that your XPath _should not_ work: https://www.w3.org/TR/xpath/#node-tests

> It should be noted that your solution requires that I first know whether my document uses namespaces, and not all of them do, and documents with them or without them remain valid. 

I hear ya, man, but take it up with the writers of the XPath 1.0 spec, not me. OTOH, I doubt there's much they'll do at this point, 18 years after the spec was published.

> All the major libraries I have tried in Java process my xpath correctly.

I don't know what libraries you're using, but they're not standards compliant if what you say is true. The built-in javax.xml.xpath APIs [require that namespaces be declared](https://stackoverflow.com/questions/23203421/javax-xml-xpath-is-not-extracted-from-xml-with-namespaces) just like in this library, as do the APIs in .NET's built-in System.Xml. I guess the creators of those javax.xml.xpath and System.Xml are standards-compliant script kiddies too.

> Lastly, if you dont like my post, delete it. But dont show everyone you are the prototypical 'kiddie' in script-kiddie by changing my title.

That's hilarious coming from someone who used the title you used and an initial post filled with vitriol.  I responded in kind. You are a pot calling the kettle black if I ever saw one. For comparison, here is the reply I gave when someone opened a very similar issue, but didn't fill it with bile: https://github.com/goto100/xpath/issues/36#issuecomment-188710185

**Comment by cmdematos** [comment]
You are right about the vitriol. I apologize, I should have checked my anger at the door. 

You are also right about registering the namespaces. The java DocumentBuilderFactory requires setNameSpaceAware(true) which I did not do. Also, it was 4 different versions of the XML, one library. I mispoke earlier.

Drat. 

Thank you for the help.

**Comment by JLRishe** [comment]
Glad to help.

In case it's not clear, you _can_ use `*[local-name() = 'ElementName']` to select elements while ignoring their namespace. So this XPath would successfully select the element, though this approach is not recommended as it is considered sloppy:

    /*[local-name() = 'project]/*[local-name() = 'version']

The trouble with the XPath you were trying was the `/project` part. That will only match an element named `project` that is in the `null` namespace, and the `project` element in your XML is not in a null namespace.
