### ISSUE TITLE
can't get text()

### ISSUE THREAD

**Issue by mgrant0** [goto100/xpath#75]
I'm using xpath.evauate() from the example something like this: 

```
var xml = "<book author='J. K. Rowling'><title>Harry Potter</title></book>"
var doc = new dom().parseFromString(xml)
var result = xpath.evaluate(
    "//title/text()",            // xpathExpression 
    doc,                        // contextNode 
    null,                       // namespaceResolver 
    xpath.XPathResult.ANY_TYPE, // resultType 
    null                        // result 
)
```

Note that I'm trying to grab the inner text of the title, "Harry Potter" by using the text() function.  It's not working with this xpath module.  This works with other xpath modules, for example xpath.js.  

The error I get is:

```
debug && console.log(node.localName + ": " + node.firstChild.data);
                                                            ^

TypeError: Cannot read property 'data' of null
at XMLParseResult (/home/mgrant/End/lisp/grc-plugins/qualys/plugin.js:196:62)
at Request._callback (/home/mgrant/End/lisp/grc-plugins/qualys/plugin.js:301:6)
at Request.self.callback (/home/mgrant/End/lisp/grc-plugins/qualys/node_modules/request/request.js:186:22)
at emitTwo (events.js:125:13)
at Request.emit (events.js:213:7)
at Request.<anonymous> (/home/mgrant/End/lisp/grc-plugins/qualys/node_modules/request/request.js:1163:10)
at emitOne (events.js:115:13)
at Request.emit (events.js:210:7)
at IncomingMessage.<anonymous> (/home/mgrant/End/lisp/grc-plugins/qualys/node_modules/request/request.js:1085:12)
at Object.onceWrapper (events.js:312:19)
```

**Comment by JLRishe** [comment]
It doesn't look like that error is coming from this library. It doesn't have a line that looks like that one in the error message and the code you pasted is running fine in RunKit: https://runkit.com/jlrishe/5a0c0fbcacdb93001233f1fa

I think I can see why there is an error - the code throwing the error is trying to access `node.firstChild.data`, but text nodes don't have any children, so `firstChild` would indeed be null. I think you're going to need to give me a bit more information about the code that's trying to use our XPath library. I tried to see if `qualys` was some package available on GitHub, but I couldn't find it.

**Comment by mgrant0** [comment]
Qualys isn't involved, that was just the name of the folder I was working in.  I probably should have removed that for clarity.  

The code I provided should be all that is needed to reproduce this.  

I want to extract just the inner text.  This text() function works in other xpath modules, just not yours.

**Comment by JLRishe** [comment]
The code you provided, on its own, doesn't reproduce this issue, as I've demonstrated. Is that actual code producing this error, or are you using some other code? If it's the latter, could you show me the actual code?

I'm pretty sure this has to do with how the result is being used and it may well be an issue in this library, but I'll need that information in order to figure out what's wrong.

**Comment by mgrant0** [comment]
Ok this turned out to be my stupid mistake, I had a console.log for debugging that was trying to output node.data.  Closing this now, thanks for the quick response!
