### ISSUE TITLE
Namespaces not working in a browser

### ISSUE THREAD

**Issue by catamphetamine** [goto100/xpath#85]
It throws on the second `select()` in a browser.

On Node.js it works.
If `a:` prefixes are removed it also works in the browser.

```js
const select = xpath.useNamespaces({
  a: 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
})
const doc = new XMLDOM.DOMParser().parseFromString(xml)
values = select('//a:si', doc)
  // `Error: XPath parse error`
  .map(string => select('.//a:t[not(ancestor::a:rPh)]', string).map(_ => _.textContent).join(''))
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="4" uniqueCount="4"><si><t>One</t></si><si><t>Two</t></si><si><t>Three</t></si><si><t>Four</t></si></sst>
```

**Comment by catamphetamine** [comment]
Edit: I checked again and actually it does return something `select('//a:si', doc)`.
The second select throws `Error: XPath parse error` though.

**Comment by catamphetamine** [comment]
So seems that it doesn't like the expression `.//a:t[not(ancestor::a:rPh)]`.
Could be a `xmldom` issue then,

**Comment by catamphetamine** [comment]
Ok, I'll just use the native XML for browser.

**Comment by catamphetamine** [comment]
Reopen if you feel like this is an issue.

**Comment by JLRishe** [comment]
@catamphetamine I suspect this is probably a node name casing issue. HTML DOMs treat all node names as being all lowercase even if the actual tags have some other casing. So I suspect that the `a:rPh` node test is failing to find the intended nodes because they have a capital P in the name.

You can probably fix this by explicitly indicating the MIME type when you parse the markup:

```js
const doc = new XMLDOM.DOMParser().parseFromString(xml, 'text/xml')
```

**Comment by catamphetamine** [comment]
@JLRishe Thanks, though I don't think it's the case.
Yesterday I was fiddling with those selectors reducing them to simple ones and still got the error in the browser (most likely I did try removing the `:not` condition).

The other thing is, yeah, I migrated it to native `DOMParser` and it worked.
Today, when I got your comment, I went to test it and replaced native `DOMParser` with this library, and when using `.evaluate()` instead of `select()` it worked for some reason.
I no longer have the old `select()` code, it has been discarded yesterday, but now I see that when using `xpath` through `.evaluate()` it no longer throws in a browser.
I'll still use the native one though just because it's the native one and is supported in most browsers (incl. IE11).
https://github.com/catamphetamine/read-excel-file/blob/9965134deffc68ced0df1a3f3393dd1a96cd99fe/source/xmlNode.js
https://github.com/catamphetamine/read-excel-file/blob/9965134deffc68ced0df1a3f3393dd1a96cd99fe/source/xmlBrowser.js

**Comment by catamphetamine** [comment]
@JLRishe Oh, actually, I just noticed: it's not using `.evaluate()` at all, seems that I moved that to simple `select()` yesterday.
So, yeah, weird, but now it works, even though using the same `.useNamespace()` and `select()`.
I guess it could have been my code after all.

**Comment by JLRishe** [comment]
@catamphetamine Thanks for the update. After re-reading your initial post, I realize that my guess about node name casing was almost definitely wrong because I now noticed that the error you were getting was an XPath parse error, and nothing in the DOM would have caused that kind of error. I guess this will just have to remain a mystery.

**Comment by catamphetamine** [comment]
> I guess this will just have to remain a mystery.
Agreed )
