### ISSUE TITLE
How to use such xpath-selectors?

### ISSUE THREAD

**Issue by ProgrammingLife** [goto100/xpath#92]
`let nodes = xpath.select('//div[@class="item-*"]', doc);`

I need all the divs which have a class where its name starts with "item-". How to do it?

**Comment by JLRishe** [comment]
`//div[contains(concat(" ", @class), " item-")]`

**Comment by ProgrammingLife** [comment]
Also I found following solution:
`let nodes = xpath.select('//book[starts-with(@class, "item-")]', doc);`

**Comment by JLRishe** [comment]
@ProgrammingLife  Your solution will not always work if the element has multiple classes.
