### ISSUE TITLE
xpath selecting text with newline

### ISSUE THREAD

**Issue by tralston** [goto100/xpath#96]
I have some xml where some nodes have attribute text with newlines. For example

```xml
<Object name="obj1" desc="1.0" />
<Object name="obj2" desc="2.0
29" />
<Object name="obj3" desc="3.0" />
```

It's import to this data to preserve the newline, since the generating application uses it to separate two different data points. When I used `xpath.select`, it returns it in one single concatenated string. So, following my example above, I would get `"2.029"` instead of `"2.0\n29"`. Since there's no newline character in the text returned from `select`, I can't split the string into separate data.

**Comment by JLRishe** [comment]
Please provide an [mvce](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by JLRishe** [comment]
@tralston Closing this due to lack of response. Please provide a repro scenario if you want to report a bug/request help.
